
continue: false
system: ./Li32Mn32O16Se32.cif
mace_model: ../../MACE-matpes-r2scan-omat-ft.model
removal_method: semi_brute_force
optimizer:
  type: FIRE2
  fmax: 0.001
  max steps: 5000
output files:
  thermo: VP/thermo.csv
  trajectory: VP/trj.xyz
  convex hull: VP/hull.csv
  voltage: VP/voltage.csv
states folder: VP/states
working ion:
  charge carried: 1
  chemical potential:
    Li: ../Li.cif
plots: true
plot_frequency: 10
voltage_max: 13.0
voltage_min: 0.5
    