continue: true
system: ./Ba8Mg16O96P24V8.cif
mace_model: ../../MACE-matpes-r2scan-omat-ft.model
removal_method: semi_brute_force
optimizer:
  type: BFGS
  fmax: 0.001
  max steps: 5000
output files:
  thermo: VP/thermo.csv
  trajectory: VP/trj.xyz
  convex hull: VP/hull.csv
  voltage: VP/voltage.csv
states folder: VP/states
working ion:
  charge carried: 2
  chemical potential:
    Mg: ../Mg.cif
plots: false
voltage_max: 6.0
voltage_min: 0.5
    
